name: Test Cable Street
favicon: null
layout_spectrum: 0.69064
typography_spectrum: 0.35919
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2a527a'
    - '#597898'
    - '#abb8c7'
  brandStrength: 0
  lightness: 0.66135463421233
  saturation: 0.31512140459381044
  rhythmicContrast: 0.6017816099338233
purpose: []
